### ISSUE TITLE
Contract changes

### ISSUE THREAD

**Issue by alrevuelta** [dappnode/mev-sp-contracts#3]
Two minor changes:
* Fix typo in `suscribe` vs `subscribe` (search, in multiple places)
* Rename all deposit address to withdrawal address (conceptually nothing changes, just a matter of naming)
* Set `ValidatorID` from `uint32` to `uint64` for consistency with the spec.
* Add sender to the subscription event (like in the unsubscription)

**Comment by invocamanman** [comment]
Added changes here: 65aa862fb207f50d43a1e38c34f47f98849c2e7f
