### ISSUE TITLE
Contract changes

### ISSUE THREAD

**Issue by alrevuelta** [dappnode/mev-sp-contracts#4]
Add the following variables to the contract, configured at deployment + **getter/setters**:
* Fees in % taken by the pool. 2 decimals. divide by 100. Examples:
  * value=333 equals to 3.33%.
* Account address taking the fees of the pool.
* Checkpoint size in slots (how often the pool is updated)
* Add block number on when the contract was deployed. This block should be before any reward went to the pool and it should change when a new contract is deployed. (side topic: check if this can be done with events)

New events:
* When fee % is modified, emit event with the new fee %. value=333 equals to 3.33%.
* Initialized event
* Pool address fee address changed.
* Checkpoint size changed.

Tentataive parameters testnet:
* fee 10%
* todo: safe in goerli: 0xE46F9bE81f9a3ACA1808Bb8c36D353436bb96091
* checkpoint size: 1 day: 7200 slots.

Also:
* Add a `slotNumber` to the `updateRewardsRoot` getter/setter function. So that when updating the merkle root, we also add the checkpoint in slots that it belongs to. A new rewards root contains the **root** and the **slot**. The getter is fine for just the last one.

**Comment by invocamanman** [comment]
this is done already ^^
